import numpy as np

# 0-1之间
m1 = np.random.rand(4,3)
print('均匀分布 4*3')
print(m1)
print('维度',m1.ndim)
print('shape',m1.shape)
print('size',m1.size)
print('dtype',m1.dtype)
m2 = np.random.randn(4,3)
print('正态分布 4*3')
print(m2)
print('ranint')
m3 = np.random.randint(4,9,12)
m3 = m3.reshape(3,4)
print(m3)

m8 = np.arange(10)
print(m8.reshape(5,2))

m4 = np.zeros((4,3))
print('全零：m4')
print(m4)

m5 = np.ones((4,3))
print('全1：m5')
print(m5)

m7 = np.eye((4))
print(m7)

m6 = np.ones_like(m1)
print('跟M1shape一样m6')
print(m6)

m9 = np.linspace(1,10,10)
print('linspace')
print(m9)
m10 = np.arange(1,101,dtype=float).reshape(10,10)
print(m10)
# 基础操作
print('m1-m2')
print(m1-m2)
print('按位乘m1*m2')
print(m1*m2)
print('矩阵乘法m1*m3')
print(m1.dot(m3))
print()
print(m1)
print('横向求和',m1.sum(axis=1))
print('纵向求和',m1.sum(axis=0))
print('横向max',m1.max(axis=1))
print('纵向max',m1.max(axis=0))
print('转置')
print(m1.T)
A = np.array([2])
print(A+m10)
print(A*m10)
print('展平',m10.ravel())
print(m10.ravel()[0])
B = np.array([[3.1,5.9,1],
              [6,3.1,4]])
print(B)
print('sortB',np.sort(B))
print('unique',np.unique(B))
print('mean',np.mean(B))
print('sqrt',np.sqrt(B))
print('square',np.square(B))
print('exp',np.exp(B))
print('abs',np.abs(B))
print('ceil',np.ceil(B))
print('floor',np.floor(B))
print('整数小数拆分')
print('modf',np.modf(B))
print('modf',np.modf(B)[0])
print('modf',np.modf(B)[1])

print('np.random')

rand = np.random.rand(5,5)
print(rand)
rand1 = np.random.randn(5,5)
print(rand1)
print('det行列式的数值')
print(np.linalg.det(rand))
print('特征值 特征向量')
print(np.linalg.eig(rand))
print('uniform')
rand2 = np.random.uniform(2,3,10)
print(rand2)
print('所有分布都有,见书签')
print('choice')
print(np.random.choice(rand2))
